repositories:
  - name: ocd-meta 
    url: https://ocd-scm.github.io/ocd-meta/charts
releases:
  - name: ocd-builder-credentials
    labels:
      secret: ocd-builder-credentials
    chart: ocd-meta/ocd-secret
    version: ~1.0.0
    values:
      - name: ocd-builder-credentials
      - env_vars: 
        - key: OPENSHIFT_SERVER
          value: "{{ requiredEnv "OPENSHIFT_SERVER" }}"
        - key: OPENSHIFT_USER
          value: "{{ requiredEnv "OPENSHIFT_USER" }}"
        - key: OPENSHIFT_PASSWORD
          value: "{{ requiredEnv "OPENSHIFT_PASSWORD" }}"
  - name: ocd-builder-realworld
    labels:
      builder: realworld
    chart: ocd-meta/ocd-builder
    version: ~1.0.0
    values:
      - source_repository_url: "http://7784f8c5766f9fc074a3d77fb426bc3058abd4a5@gitea-ocd-builder.192.168.99.100.nip.io/simbo1905/env-build.git"
      - "ocd-builder/realworld.io/realworld-builder.yaml"
      - "ocd-builder/realworld.io/app_key.yaml"
    hooks:
    - events: ["prepare"]
      command: "/bin/sh"
      args: ["-c", "{{ requiredEnv "OCD_SCRIPTS_PATH" }}/ocd-prepare-hook.sh && {{ requiredEnv "OCD_CHECKOUT_PATH" }}/import-image.sh"]
