#!/bin/bash

# debug logging
set +x

# delete the unencrypted secrets
${OCD_SCRIPTS_PATH}/ocd-delete-secrets.sh

# this wrapper will detected session timeout and login
oc() { 
    ${OCD_SCRIPTS_PATH}/oc_wrapper.sh "$@" 
}

sleep 1

# tag the generic webhook image as the specific webhook image 
oc tag ocd-builder-webhook:latest ocd-builder-webhook-realworld:latest

# deploy the webhook
oc rollout latest dc/ocd-builder-webhook-realworld -n $PROJECT

# expose the webhook with a route
oc expose svc ocd-builder-webhook-realworld
