#!/bin/bash

# debug logging
set +x

# this wrapper will detected session timeout and login
oc() { 
    ${OCD_SCRIPTS_PATH}/oc_wrapper.sh "$@" 
}

# delete the unencrypted secrets
${OCD_SCRIPTS_PATH}/ocd-delete-secrets.sh

# deploy the webhook
oc rollout latest dc/ocd-builder-webhook-realworld -n $PROJECT

# expose the webhook with a route
oc expose svc ocd-builder-webhook-realworld

