repositories:
  - name: ocd-meta 
    url: https://ocd-scm.github.io/ocd-meta/charts
releases:
  - name: realworld-react-redux
    labels:
      builder: realworld-react-redux
    chart: ocd-meta/ocd-builder
    version: ~1.0.0
    # note that app_key.yaml is encrypted as app_key.yaml.secret in git
    values:
      - "realworld-builder.yaml"
      - "app_key.yaml"
      - source_repository_url: http://c9b58970a1ea91c9b93f78b400a52b3db7db33b0@gitea-gitea.192.168.99.101.nip.io/simbo1905/realworld-react-redux.git
  - name: realworld-react-redux-webhook
    labels:
      ocd-builder-webhook: realworld-react-redux
    chart: ocd-meta/ocd-builder-webhook
    version: ~1.0.0
    values:
      - name: webhook-realworld-react-redux
      - webhookRepFullname: simbo1905/realworld-react-redux
      - buildNamespace: {{ requiredEnv "PROJECT" }}
      - build: realworld-react-redux
      - insecureSkipTlsVerify: true
      - webhookSecret: 2lqH2Erp3E
      - deploy_env: 
        - name: OPENSHIFT_SERVER
          value: "{{ requiredEnv "OPENSHIFT_SERVER" }}"
