repositories:
  - name: ocd-meta 
    url: https://ocd-scm.github.io/ocd-meta/charts
releases:
  - name:  {{ requiredEnv "ENV_PREFIX" }}-realworld
    labels:
      builder: realworld
    chart: ocd-meta/ocd-builder
    version: ~1.0.0
    # note that app_key.yaml is encrypted as app_key.yaml.secret in git
    values:
      - "realworld-builder.yaml"
      - "app_key.yaml"
      - source_repository_url: {{ requiredEnv "OCD_GIT_REPO" }}
      - openshiftServer: "{{ requiredEnv "OPENSHIFT_SERVER" }}"
      - project: {{ requiredEnv "PROJECT" }}
  - name: {{ requiredEnv "ENV_PREFIX" }}-realworld-webhook
    labels:
      ocd-builder-webhook: realworld
    chart: ocd-meta/ocd-builder-webhook
    version: ~1.0.0
    values:
      - name: webhook-realworld
      - webhookRepFullname: simbo1905/realworld-react-redux
      - buildNamespace: {{ requiredEnv "PROJECT" }}
      - build: realworld
      - insecureSkipTlsVerify: true
      - webhookSecret: 2lqH2Erp3E
      - deploy_env: 
        - name: OPENSHIFT_SERVER
          value: "{{ requiredEnv "OPENSHIFT_SERVER" }}"
