#!/bin/bash
set +x
# run the defaults that will try to gpg decrypt any *.secret files it finds
${OCD_SCRIPTS_PATH}/ocd-decrypt-secrets.sh
# import the s2i image for this project which may already exist
${OCD_CHECKOUT_PATH}/realworld-react-redux/import-image.sh
