#!/bin/bash

# debug logging
set +x

# delete the unencrypted secrets
${OCD_SCRIPTS_PATH}/ocd-delete-secrets.sh

# this wrapper will detected session timeout and login
oc() { 
    ${OCD_SCRIPTS_PATH}/oc_wrapper.sh "$@" 
}

# sleep 1

# # tag the generic webhook image as the specific webhook image 
# oc tag ocd-builder-webhook:latest webhook-realworld-react-redux:latest

# # deploy the webhook
# oc rollout latest dc/webhook-realworld-react-redux -n $PROJECT

cowsay "All done!"